fix: replace structuredClone with Object.assign
dotlottie/player-component pull request #258
Opened 2023-11-04 15:25 UTC by yash1200

## Description

Replaces structuredClone with Object.assign in dotlottie-player.ts
Fixes - #256 

## Type of change

Affects `common/src/dotlottie-player.ts`

- [x] Patch: Bug (non-breaking change which fixes an issue)
- [ ] Minor: New feature (non-breaking change which adds functionality)
- [ ] Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Docs: Documentation updates (if none of the other choices apply)

## Checklist

- [ ] Lint and unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have tested my changes on the player-component and React player.

2023-11-04 16:16 UTC, theashraf requested changes
Thank you for your PR.

I have just one small comment: please kindly add a changeset to each of the packages to increment the patch version.
For contribution guidelines, refer to: https://github.com/dotlottie/player-component#contributing

2023-11-04 16:16 UTC, theashraf commented on .eslintrc.js
> +    'prefer-object-spread': 'off',
```suggestion
    'prefer-object-spread': 'warn',
```

2023-11-05 06:49 UTC, dnepromell commented on packages/common/src/dotlottie-player.ts
> +    else this._src = Object.assign({}, src);
```suggestion
    this._src = typeof src === 'string' ? src : Object.assign({}, src);
```

2023-11-05 06:51 UTC, dnepromell commented on packages/common/src/dotlottie-player.ts
> +    else this._src = Object.assign({}, src);
this._src = typeof src === 'string' ? src : Object.assign({}, src);

2023-11-06 05:20 UTC, theashraf approved these changes

2023-11-06 05:20 UTC, merged